### ISSUE TITLE
run the sample data, has a keyerror

### ISSUE THREAD

**Issue by flamehaze1115** [facebookresearch/AR-Depth#1]
I download the whole rep and the sample data. Following the instructions, I run all the cells. However I met a keyerror. PS: I found that the first line in "images.txt" is 000009.png, not 000000.png.
As below:

Number of points: 62786
Number of frames: 691
Processing frame 000009.png

KeyError                                  Traceback (most recent call last)
<ipython-input-12-23865dc9a87b> in <module>()
      5 for frame in recon.ViewIds():
      6     print "Processing frame " + recon.views[frame].name
----> 7     kfs = recon.GetReferenceFrames(frame)
      8     if (len(kfs) == 0):
      9         continue

<ipython-input-10-1d526638ec99> in GetReferenceFrames(self, view_id)
     24 
     25     def GetReferenceFrames(self, view_id):
---> 26         kf = self.GetNeighboringKeyframes(view_id)
     27         dist = np.linalg.norm(self.views[kf[1]].Position() -                              self.views[kf[0]].Position()) / 2
     28         pos = self.views[view_id].Position()

<ipython-input-10-1d526638ec99> in GetNeighboringKeyframes(self, view_id)
     12         next_keyframe = -1
     13         for idx in range(view_id - 1, 0, -1):
---> 14             if self.views[idx].IsKeyframe():
     15                 previous_keyframe = idx
     16                 break

KeyError: 7

**Comment by holynski** [comment]
Thanks for the note - I'll look into this now.

**Comment by holynski** [comment]
Please follow issue #2. I'm actively working on resolving this issue now.

**Comment by flamehaze1115** [comment]
> Please follow issue #2. I'm actively working on resolving this issue now.

Thank you very much.

**Comment by holynski** [comment]
Closing, refer to issue #2.
