### ISSUE TITLE
Wrong results when value is negative using maximum in GetImageGradient function 

### ISSUE THREAD

**Issue by huayong** [facebookresearch/AR-Depth#3]
If rgb gradients all are positive, maximum get max gradient. But If rgb gradients all are negative, maximum get min gradient.
It seems that the code is not correct.

**Comment by holynski** [comment]
Thanks for pointing this out -- I just pushed a fix. Can you confirm that it's now doing what it should?

**Comment by huayong** [comment]
Thanks for your reply and revision.
I have checked the results using AbsoluteMaximum function, it's right.
And I think you also should update the maximum to AbsoluteMaximum in Canny function.

**Comment by holynski** [comment]
There, I added that one too. 

Does that fix everything?

**Comment by huayong** [comment]
Yeah.

**Comment by holynski** [comment]
Cool, closing the issue.
